[users]
natasha = { password = "1234", centro = "Calle Belén", nombre = "Natasha Carrari" }
estefania = { password = "1234", centro = "Calle Belén", nombre = "Estefanía Eberle" }
martin = { password = "1234", centro = "Calle Belén", nombre = "Martín Pérez Santellán" }

camila = { password = "1234", centro = "Nudo a Nudo", nombre = "Camila Prada" }
julieta = { password = "1234", centro = "Nudo a Nudo", nombre = "Julieta" }

florencia = { password = "1234", centro = "Casa Maranatha", nombre = "Florencia" }
guillermina = { password = "1234", centro = "Casa Maranatha", nombre = "Guillermina Cazenave" }
admin = { password = "1234", centro = "Administrador", nombre = "Alejandro" }
