[users]

admin = { password = "Hogar2025!", role = "admin", centers = ["*"] }

natasha = { password = "hogar", role = "coord", centers = ["Calle Belén"] }
estefania = { password = "hogar", role = "coord", centers = ["Calle Belén"] }
martin = { password = "hogar", role = "coord", centers = ["Calle Belén"] }

camila = { password = "hogar", role = "coord", centers = ["Nudo a Nudo"] }
julieta = { password = "hogar", role = "coord", centers = ["Nudo a Nudo"] }

florencia = { password = "hogar", role = "coord", centers = ["Casa Maranatha"] }
guillermina = { password = "hogar", role = "coord", centers = ["Casa Maranatha"] }
